name: Upload to codecov

on:
  - push

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/logs/clover.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
